### ISSUE TITLE
Paths according to different impact parameter

### ISSUE THREAD

**Issue by yujin512** [bmorris3/stash#8]
[
![20140905_050000_ic_flat_4k](https://user-images.githubusercontent.com/29724761/44358116-e2988300-a468-11e8-823e-09fdbc5a9f43.jpg)
](url)

I am looking for spotless days during the solar maximum, and it's really difficult to find completely clean days. So I was wondering what the transit path looks like according to different impact parameters! For instance, does it go up to the top half like the image above or does it cover the bottom half? It'd be easier to find images with a clean northern hemisphere!

**Comment by bmorris3** [comment]
Sorry I didn't answer this promptly. The impact parameter moves the planet on a parallel path to your b=0 line, and you can vary it on the range [-1, 1] to go from crossing the bottom of the sun to the top of the sun.
